### ISSUE TITLE
Краткое содержание тем слушателей с ChatGPT

### ISSUE THREAD

**Issue by ufian** [radio-t/super-bot#101]
Это отдельный таск для расширения интеграции с OpenAI #93 

**Проблема**

Слушатели постят темы, которые не все ведущие читали. Когда содержание слишком длинное, то ведущие пропускают тему без обсуждения.

**Идея решения**
Чтобы было можно хотя бы что-то обсудить, можно использовать OpenAI API (ChatGPT) для построения саммари каждой темы от слушателей. Подобный функционал уже сейчас реализован @umputun для краткого изложения основной выбранной темы.

**Путь решения**
1. Когда происходит событие "выбраны темы слушателей", то запросить через API список комментариев
2. Из комментариев выбрать ссылки и достать из них контент
3. Из контента сделать краткое изложение с помощью ChatGPT
4. Запостить результат в чат

**Comment by ufian** [comment]
**Размышления на тему решения этой задачи**
1. Для извлечения контента нужно использовать [ukeeper-readability](https://github.com/ukeeper/ukeeper-readability), это требует время существенное время. Поэтому хорошо бы распаралелить
2. Для OpenAPI call тоже нужно время и тоже хорошо бы распаралелить
3. Мне на данный момент не очень понятно как интегрироваться с сигналами во время записи подкаста. Не исключено, что из-за пунктов 1 и 2 после выбора тем слушателей придётся долго ждать их краткое описание.
4. И чисто стилестический вопрос как выводить результат: одним или многожеством сообщений. Что включать в выдачу итп

**Comment by umputun** [comment]
> Мне на данный момент не очень понятно как интегрироваться с сигналами во время записи подкаста. Не исключено, что из-за пунктов 1 и 2 после выбора тем слушателей придётся долго ждать их краткое описание.

это просто, смотри активацию для выбранных тем, так-же выбирается и темы слушателей https://github.com/radio-t/super-bot/blob/master/app/events/rtjc.go#L53

> И чисто стилестический вопрос как выводить результат: одним или многожеством сообщений. Что включать в выдачу итп

Я думаю, отдельными. Это будет в паралель просиходить, но резултаты нужны сортированные по рейтингы коментов

**Comment by umputun** [comment]
> Для извлечения контента нужно использовать [ukeeper-readability](https://github.com/ukeeper/ukeeper-readability), это требует время существенное время.

Ну, это определенный загиб. Время там не особо тратится, по сравнению с тем, что займет gpt запрос эти миллисикунды роли не играют особой

**Comment by ufian** [comment]
Мой локальный эксперимент показывает, что на выдирание контента нужно несколько секунд, если ссылка не знакомая. При этом полная генерация по темам слушателей заняла 6 минут. Здесь нужно подумать как сделать оптимальнее

Другая проблема - это вид сообщений. Я хотел запихнуть оригинальный markdown в текст сообщения, но в половине случаев телеграм на это ругается. Возможно поможет переезж на MarkdownV2 но я не уверен.

Текущий вид сообщений
![image](https://user-images.githubusercontent.com/1496873/229334334-8b6a6675-d35c-4163-9299-8214d91ffafb.png)

**Comment by umputun** [comment]
> Я хотел запихнуть оригинальный markdown в текст сообщения, но в половине случаев телеграм на это ругается.

В этом деле @paskal специалист. Насколько я помню, подобную проблему в feed-master он решил посылокй html в тг. Из маркдауна его можно рендерить. Если я ничего не путаю, в тг какой-то странный маркдаун

> на выдирание контента нужно несколько секунд, если ссылка не знакомая

Если речь идет о вызове `https://ureadability.radio-t.com/api/content/v1/parser` то так быть не должно и ничего бизкого к "несколько секунд" я не наблюдаю, ну если конечно 1s total не подпадает под "несколько".

```
> time http "https://ureadability.radio-t.com/api/content/v1/parser?token=*******&url=https://www.thecodedmessage.com/posts/stroustrup-response/" > /dev/null
http  > /dev/null  0.15s user 0.03s system 17% cpu 1.067 total

> time http "https://ureadability.radio-t.com/api/content/v1/parser?token=*******&url=https://www.zdnet.com/article/i-tested-google-bard-it-was-surprising-in-a-bad-way/" > /dev/null
http  > /dev/null  0.15s user 0.03s system 14% cpu 1.227 total
```

При этом, больше половины времени это посылка результата. При запуске локально (а именно так оно и будет в ральной жизни), время в районе 300-500мс

**Comment by paskal** [comment]
Маркдаун нужно очищать от всего что не включено в их стандарт, это мудрёный процесс. В go-pkgz/notify я делаю рендер в html и оттуда уже вычищаю всё недозволенное:

https://github.com/go-pkgz/notify/blob/c1c78ac/telegram.go#L135-L142

**Comment by ufian** [comment]
@paskal Спасибо за наводку! Я прямо ваш код заимпортировал для подготовки html

<img width="455" alt="Screenshot 2023-04-02 at 8 56 37 PM" src="https://user-images.githubusercontent.com/1496873/229408045-45ccb644-5a93-45a9-a2a0-23a4d88a420c.png">
