### ISSUE TITLE
Добавить тестов

### ISSUE THREAD

**Issue by umputun** [radio-t/super-bot#12]
Покрытие тестами оставляет желать.

Поскольку мы в процессе перехода на телеграм #3 , то имеет смысл это делать в бренче `telegram` и не трогать master пока они не слиты.

**Comment by spiritofsim** [comment]
@umputun , как ты смотришь на использование
[github.com/golang/mock](https://github.com/golang/mock) вместо [github.com/stretchr/testify/mock](https://github.com/stretchr/testify/mock)

у первого, как мне кажется, более внятный интерфейс. По крайней мере не нужно передавать имя метода в виде стоки как вот тут: `mockHttp.On("Do", mock.Anything)`

**Comment by umputun** [comment]
не особо положительно. Во первых, testify уже часть зависимостей тестирования и читатель кода, видя testify повсюду резонно может ожидать использование и mock от testify. Во вторых, я как-то столкнулся с каким-то WTF от testify/mock и попробовал решать это через golang/mock. Там все совершенно иначе, с одной стороны, и менее гибко, с другой. И в последних - мне не кажется существенной проблемой для мока передавать имя функции строкой, и в общем и целом, интерфейс  testify/mock мне видится гораздо более внятным.

**Comment by umputun** [comment]
покрытие теперь вполне пристойное
