### ISSUE TITLE
Вопрос: включение отключение отдельных функций бота.

### ISSUE THREAD

**Issue by alexkart** [radio-t/super-bot#120]
Есть ли в боте возможность простого отключения различных функций? Например, я хочу оставить только функциональность связанную с ChatGPT, чтобы бот слушал чат и иногда отвечал на сообщения, а все остальные функции, такие как определение спама, баны и т.д. отключить. Возможно ли это сделать с помощью конфигурации или переменных окружения, или для этого необходимо вносить изменения в код? Если необходимо менять код, то насколько сложно это сделать? Достаточно ли просто где-то закомментировать подключение определенных модулей или нужно много кода переписывать?

**Comment by umputun** [comment]
этот бот не предназначен для широкого использования вне инфраструктуры подкаста, потому необходимости конфигурирования в нем особо и нет. Все, что доступно для конфигурации можно найти тут https://github.com/radio-t/super-bot/blob/master/app/main.go#L31

я бы советовал просто написать отдельный бот для ChatGPT, скопировав код себе по необходимости
