### ISSUE TITLE
Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

### ISSUE THREAD

**Issue by umputun** [radio-t/super-bot#20]
![606u6-202001-31175515-6423f](https://user-images.githubusercontent.com/535880/73582452-dd5ba800-4452-11ea-8164-3a2ec6cf080c.png)

@chuhlomin это что-то поломалось от #18? Посмотри, плз в чем там дело

**Comment by chuhlomin** [comment]
Нет, это ошибка из самой библиотеки `telegram-bot-api`: https://github.com/go-telegram-bot-api/telegram-bot-api/blob/master/bot.go#L505
Воспроизвел локально запустив два бота с одним и тем же токеном.

**Comment by umputun** [comment]
однако, я не запускал два бота, у меня только один

**Comment by umputun** [comment]
таки я. После обновления MacOS и перезагрузки поднялся автоматом один из контейнеров что я тестировал давно и начал гадить.
