### ISSUE TITLE
Функция пина для сообщения о начале вещания

### ISSUE THREAD

**Issue by Semior001** [radio-t/super-bot#23]
Предлагаю добавить для бота broadcast_status пин на сообщение о начале вещания.
Практическая ценность - те, у кого чат замьючен (а это, я думаю, поголовно все) не увидят сообщение о начале вещания покуда не взглянут в чат.
Если бот будет пинить данное сообщение, то тогда уведомление получат все участники чата.
Проблема в том, что текущий интерфейс не позволяет пинить какие бы то ни было сообщения:
```go
// Interface is a bot reactive spec. response will be sent if "send" result is true
type Interface interface {
	OnMessage(msg Message) (response string, send bool)
	ReactOn() []string
}
```

**Comment by umputun** [comment]
Мы можем поменять результат OnMessage чтоб он возвращал структуру, типа

```
type Response struct {
  Send bool
  Text string
  Pinned bool
 ....
}
```

**Comment by Semior001** [comment]
как поступать в случае pin=true, когда бот собирает сообщения? он не сможет прихватить что-то, что не является сообщением о старте вещания?
