### ISSUE TITLE
Бот посылающий сигнал о начале сбора тем к выпуску

### ISSUE THREAD

**Issue by umputun** [radio-t/super-bot#28]
Он может делать site-api call время от времени для podcast и prep, и если появился prep в последние N минут и еще не сообщал - сообщит в виде "Сбор тем для #123 начался" (с ссылкой внутри). Mожно и припинить после того, как #25 будет влит.

вызов site-api примерно такой: `https://radio-t.com/site-api/last/5?categories=podcast`

**Comment by grayru** [comment]
Учитывая, что ты контролируешь все части — зачем надо делать много pull, если можно сделать один push?
Прикрути к сайту отправку сообщения ботом в чат сразу после поста. Тем более, что все равно какое-то сообщение про новый выпуск же уходит.

**Comment by umputun** [comment]
никакого сигнала от сайта не приходит, этот сигнал (про кат) от news, о начале/конце вещания это pull из icecast. Технически проще (и надежнее) делать pull и тут.

**Comment by grayru** [comment]
Почему проще и надежнее делать пару сотен запросов, как минимум, к сайту и потом как-то парсить результат, чем один раз со стороны сайта прислать отформатированное сообщение в бот?

**Comment by umputun** [comment]
поясню, почему "Технически проще (и надежнее)"

- при pull все, что надо делать это раз в минуту http GET который уже есть и уже возвращает подходящий ответ, который даже не надо парситъ (unmarshal json). Т.е. никаких изменений не надо делать со стороны site-api (сервера)
- Дописать подобный сервер на стороне бота, чтоб инвертировать логику (push) в принципе несложно, но это будет совершенно особый бот, чем-то похожий на rtjc (тот, что слушает от news) который вообще не бот и который такой диковинный по причинам историческим. Подобного (необычного) добавлять не хочется
-  По поводу надежней - ситуация с push со стороны site-api должна будет поддерживатъ репеатер и, скорее всего должна быть асинхронной операцией. Это надо для того, чтоб не потерять сигнал если бот мертв в этот момент. 
- Для пул, этого всего не надо, эту операцию можно сделать весьма надежной тем простым способом, что описан в тикете. Т.е. если бот не лежит дольше 5 минут в момент добавления темы про выпуски, он ее получит. 5ти минутное окно выбрано для упрощеня (не надо никакого persistent state)
- "пару сотен запросов, как минимум, к сайту " - это не запросы к сайту, но к существующему site–api. Никакого парсинга сайте тут не просиходит. В тикете приведен реальный url который возвращает готовый json.
- строго говоря запросов будет 60 в час, т.е. 1440 в сутки. Это число не волнует вообще никак, тут не стоит ничего оптимизировать т.к. нет проблемы.

Теоретически, завести подобный push бот это неплохая идея. Она не так проста как кажется, т.е. надо будет подумать об ограничении доступа каким-то образом, лимитерах против злодеев (и наших ошибок), и как подобный бот вообще  интегрировать в существующий интерфейс. Для этой конкретной задачи, такая работа выглядит неоправданно сложной и не вносящй видимых бенефитов.

**Comment by grayru** [comment]
Ты как-то странно считаешь. На данный момент есть вот такие вещи в боте, которые происходят потому, что на сайте/news что-то происходит:
— старт темы слушателей — пока не происходит, но вот обсуждаем же.
— старт эфира (кат) и дальше выбор каждой темы в news.
— публикация очередного выпуска.

Я подозреваю, что вторая часть решается как-то очень кастомно, а третья просто делается твоими руками. И мне кажется очевидным, что гораздо проще решить эти вопросы реализацией на стороне бота, который будет получать готовый message для постинга от движка сайта, когда и если там что-то будет происходить.

**Comment by umputun** [comment]
я не очень понял, что именно странно. Все, что ты привел не относится к site-api. Кат и темы (в томе числе темы слушателей) это news через пуш, который весьма кастомный и который тот самый, rtjc пришедший с времен jabber.  По хорошему, его тоже стоит переделать в нормальный бот, который будет делать news длинный pull, как делает UI. Просто пока руки не дошли и не было причин этим заморачиваться.

публикация очередного выпуска - это вообще с ботом не связанно никак. Там свой процесс, который даже теоретически не делается ботом (или как минимнум бот tg api) и происходит он от того прцесса, что читает фид. Даже если закрыть глаза на то, что это не делается технически, мне это e`e и кажется неправильным местом, т.е. давать боту такую функциональность я вообще не хочу, он про другое.

>  И мне кажется очевидным, что гораздо проще решить эти вопросы реализацией на стороне бота, который будет получать готовый message для постинга от движка сайта, когда и если там что-то будет происходить.

Нет, это гораздо сложнее решить. Кроме того, "движка сайта" у нас нет вообще, это статика. То, что я приводил это site-api, т.е. API server, a вовсе не активный клиент, который нбадо делать для пуша.

**Comment by spiritofsim** [comment]
@umputun , а https://radio-t.com/site-api/last/5?categories=**prep** не будет достаточно?
Как нужно использовать https://radio-t.com/site-api/last/5?categories=**podcast** ?

Кстати, а где-то есть описание api?

**Comment by umputun** [comment]
> а https://radio-t.com/site-api/last/5?categories=prep не будет достаточно?

Идея в том, чтоб одним вызовом взять последние выпуыски и темы и проверить, что последний prep идет за подакстом. Это значит, что открыт сбор тем. Если сделать просто prep мы и получим только темы без понимания о том, был ли подкаст после них.

Т.е. вызов должен быть такой: `https://radio-t.com/site-api/last/5?categories=podcast,prep`

> Кстати, а где-то есть описание api?

https://radio-t.com/api-docs/

**Comment by spiritofsim** [comment]
Ок, спасибо. Займусь

**Comment by spiritofsim** [comment]
Кстати, а зачем определять что prep идет после podcast? На сколько я понял, это всегда так (они чередуются). Т.е. в принципе можно ограничиться вызовом https://radio-t.com/site-api/last/1?categories=podcast,prep
и если категория prep, то идет сбор тем.

**Comment by umputun** [comment]
да, скорее всего будет работать
