### ISSUE TITLE
Добавить поддержку telegram

### ISSUE THREAD

**Issue by umputun** [radio-t/super-bot#3]
Хотелось бы уметь запускать с телеграмом. Нет цели поддерживать одновременно оба чата и нет цели их синхронизировать.

Все, что хотелось бы добиться:

1. Работа авто-ботов отвечающих на все то, на что отвечал гиттер. Эта часть почти работает в бренче telegram, хотя весьма минимальна и, скорее всего, с форматированием ответов там могут быть проблемы. 
1. Подключить telegram к reporter (то, что строит лог чата). Не уверен какие там будут проблемы 
1. Добавить API и UI для замены chat.radio-t.com

**Comment by umputun** [comment]
еще Rtjc (то, что слушает api новостей) надо адаптировать под телеграм

**Comment by grayru** [comment]
Пункт 2 выглядит устрашающе — как предлагается смешать два отдельных чата в одном логе?

**Comment by Jaitl** [comment]
По поводу пункта 2:
1. Нужно ли сохранять в report сообщения от самого бота? (в телеграме бот не получает сообщения других ботов и текущая логика с сохранением с сохранением в report своих же сообщений работать не будет) https://core.telegram.org/bots/faq#what-messages-will-my-bot-get
2.  Нужно ли сохранять в report аудио, видео, фотки и прочий медиа контент, если да то как?

По поводу пункта 3:
Тут подразумевается сделать свою веб версию телеграм чата? или что то проще? Щас там просто встроена веб версия гиттера, на сколько я понимаю с телеграммом такое сделать не получится.

**Comment by umputun** [comment]
> Пункт 2 выглядит устрашающе — как предлагается смешать два отдельных чата в одном логе?

это не предполагается вообще. Бот не будет это делать одновременно для разных источников и один бот (контейнер) вообще не будет сразу поддерживать оба канала общения.

**Comment by umputun** [comment]
@Jaitl да,  сохранять в report сообщения от самого бота нужно. По поводу прочих типов (кроме теста) - хорошо бы уметь картинки. По поводу "то как" - понятия не имею. Сейчас они сами собой работают как ссылки на внешние `img`. Я подозреваю, что для телеграма это работать не будет и тут это будет частью нового API что нам в любом случае нужен для пункта 3

**Comment by chuhlomin** [comment]
> 3. Добавить API и UI для замены chat.radio-t.com

Сейчас на chat.radio-t.com embed-версия Gitter и "панелька с вещанием".
Насколько я знаю телеграм нельзя просто так встроить в веб страницу.
Что подразумевается делать? Есть такие идеи:
1. Редирект в группу в телеграме – дешево и сердито
2. Как-то в реальном времени рендерить то что собирает в логи radio-t bot (только текст и картинки)
3. Делать то же самое, но собирать и рендерить вообще все что можно – долго и сложно

**Comment by umputun** [comment]
пункт 2 наше все. По поводу "как-то рендерить" - это надо оставить на ответственность фронетенда. Наша цель пока, это предоставить удобный backend/api для этого. Самый незамысловатый способ, что приходит в голову это релизовать SSE https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events 

Я подобное делал [вот тут](https://github.com/umputun/remark/pull/336) и мне кажется, что будет работать неплохо для подобных стримов обновления чата.

**Comment by umputun** [comment]
Еще одно - надо добавить в README инструкции по подключению бота к tg.

**Comment by Semior001** [comment]
предлагаю добавить для бота пин на сообщение о запуске ката
практическая ценность - те, у кого чат замьючен (а это, я думаю, поголовно все) не увидят сообщение о начале вещания покуда не взглянут в чат
если бот будет пинить данное сообщение, то тогда уведомление получат все участники чата
проблема в том, что текущий интерфейс не позволяет пинить какие бы то ни было сообщения:
```go
// Interface is a bot reactive spec. response will be sent if "send" result is true
type Interface interface {
	OnMessage(msg Message) (response string, send bool)
	ReactOn() []string
}
```
