### ISSUE TITLE
Slow mode в чате между выпусками

### ISSUE THREAD

**Issue by alff0x1f** [radio-t/super-bot#37]
Не знаю, нужно ли, предложу просто как идею.

В телеграме есть так называемый slow mode - для чата можно установить минимальное время между сообщениями пользователя. От 10 сек до 1 часа. То есть если написал сообщение, то следующее можешь написать только через время, указанное в настройке slow mode.

Мне видится здравой идеей чтобы бот ставил slow mode в промежутках между выпусками, дабы чат не уходил во флуд и холивары на отвлеченные темы.

Но это на усмотрение ведущих, конечно же, открыл issue скорее для того чтобы показать что есть такая возможность.

**Comment by umputun** [comment]
Я не очень понимаю, какую проблему замедление чата решает и чем оно поможет, кроме того, что отобьет желание туда писать.

В активности чата между выпусками нет беды, это наооборот хорошо. А флуда и холиваров на отвлеченные темы в групповом чате не избежать, хотя в нашем чате это пока не проблема которую надо решать
