### ISSUE TITLE
Добавление новой команды

### ISSUE THREAD

**Issue by catexis** [radio-t/super-bot#40]
Команда для бота `/wtf`
Описание для `/help`: команда с ожидаемым результатом
Реализация: после ввода команды - пользователь, который её ввёл банится на время от 5 минут до часа (random). Команда будет полностью отражать суть мыслей того кто её ввёл: `wtf?`

**Comment by umputun** [comment]
как-то она неправильно работает. На некоторых вообще не реагирует и я подозреваю, это что-то с их именем не так и проблема скорее всего со всеми ботами.

`[WARN]  failed to respond on update, can't send message to telegram: Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 4`

И оно говорит что банит, но не банит, тоже непонятно от чего. 

@chuhlomin поглядишь что там не так? я подозреваю, что мой прошлый рефакторинг просто поломал бан

**Comment by chuhlomin** [comment]
> `[WARN] failed to respond on update, can't send message to telegram: Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 4`

это исправил в #44 

> говорит что банит, но не банит

это исправил в #43

**Comment by umputun** [comment]
thx @chuhlomin
