### ISSUE TITLE
Идея как избежать спама от бота в чатике

### ISSUE THREAD

**Issue by bessarabov** [radio-t/super-bot#41]
Сейчас в чате все прям плохо — куча лишних сообщений. Кто-то спрашивает бота какою-то команду /who /help или что-то такое, а потом народ тыкает в эту команду и все повторяется снова. Все эти слеш команды в телеграме выглядят как ссылка и собственна говоря ей и являются — один неосторожный клик и появляется спам в чате.

![Screenshot 2020-02-13 at 21 53 07](https://user-images.githubusercontent.com/47263/74468098-4a3b5d00-4eab-11ea-9700-2b544353890a.png)

Но! Как я только что убедился есть слеш команда `/доколе` — она работает, бот на нее регирует, но при этом телеграм не выделяет ее сининьким.

![Screenshot 2020-02-13 at 21 52 39](https://user-images.githubusercontent.com/47263/74468116-51626b00-4eab-11ea-9911-f33654ec98cd.png)

Так что моя идея — давайте все слеш команды сделаем на русском языке. На мой взгляд это избавит от лишнего шума в чате.

**Comment by alexeyten** [comment]
Можно просто убрать команды со слешами и оставить только с восклицательными знаками

**Comment by bessarabov** [comment]
Да, отличная мысль. 

Текущий список команд:

```
/news, /новости, news!, новости! – 5 последних новостей для Радио-Т
/joke, /chuck, /анекдот, анекдот!, анкедот!, joke!, chuck! – расскажет анекдот или шутку
/so, so! – 1 случайный вопрос со StackOverflow
/ddg, ddg!, ?? – поискать на DuckDuckGo, например: /ddg lambda
/search, search! – искать в описаниях подкастов, например: /search lambda
/say, say! – набраться мудрости
/ping, ping – ответит pong
/пинг, пинг – ответит понг
/who, /кто, кто?, who? – ведущие Радио-Т
/when, /когда, когда?, when? – расписание эфиров Радио-Т
/how, /как, как?, how? – online вещание Радио-Т
/доколе, доколе? – день закрытия Радио-Т
/rules, /правила, rules?, правила? – правила общения в чате
```

![Screenshot 2020-02-13 at 23 25 10](https://user-images.githubusercontent.com/47263/74475243-19adf000-4eb8-11ea-97e6-1590252899ad.png)

**Comment by bessarabov** [comment]
Класс. Спасибо!
