### ISSUE TITLE
бот поиска по подкастам иногда неправильно выводит темы

### ISSUE THREAD

**Issue by umputun** [radio-t/super-bot#50]
В некоторых случаях запрос выводит названия, но не может найти подходящие темы

Например, запрос `search! всё` выводит такое
<img width="413" alt="Screen Shot 2020-03-07 at 3 07 06 AM" src="https://user-images.githubusercontent.com/535880/76140496-bc254300-6020-11ea-8778-34564abb6875.png">

Скорее всего проблема в том, что поиск через site-api делает это по монговой логике полнотекстового поиска, и додумывает разное странное, типа "всё" и "все" это, похоже, для него одно и тоже.

Простое решение не выводить выпуски про которые нет совпадений по темам.

**Comment by spiritofsim** [comment]
@umputun, в мастере тесты не проходят.
Соответственно пайплайн на мой PR упал (

**Comment by umputun** [comment]
хмм? в акаком смысле "не проходят"? вот последний тест мастера https://github.com/radio-t/super-bot/runs/556841898?check_suite_focus=true

Твой бренч падает на 

--- FAIL: TestPodcastBotReturnsOnlyTopicsWithSearchedNotes (0.00s)

**Comment by spiritofsim** [comment]
Очень странно. сейчас специально склонировал проект
git clone https://github.com/radio-t/super-bot
go test ./... падает с множеством ошибок.
например:
 sys_test.go:15:                                                                                                                                                                                                       Error Trace:    sys_test.go:15                                                                                                                                                                            Error:          Not equal:                                                                                                                                                                                                expected: bot.Response{Text:"_pong_", Send:true, Pin:false, Unpin:false, Preview:false, BanInterval:0}                                                                                                    actual  : bot.Response{Text:"_pong_\r", Send:true, Pin:false, Unpin:false, Preview:false, BanInterval:0}                                                                                                                                                                                                                                                                                                            Diff:                                                                                                                                                                                                     --- Expected                                                                                                                                                                                              +++ Actual                                                                                                                                                                                                @@ -1,3 +1,3 @@                                                                                                                                                                                            (bot.Response) {                                                                                                                                                                                         - Text: (string) (len=6) "_pong_",                                                                                                                                                                        + Text: (string) (len=7) "_pong_\r",                                                                                                                                                                        Send: (bool) true,                                                                                                                                                                      Test:           TestSys_OnMessage                     


что я делаю не так? (

**Comment by paskal** [comment]
```
➜  Desktop git clone https://github.com/radio-t/super-bot
Cloning into 'super-bot'...
remote: Enumerating objects: 95, done.
remote: Counting objects: 100% (95/95), done.
remote: Compressing objects: 100% (66/66), done.
remote: Total 1288 (delta 56), reused 61 (delta 29), pack-reused 1193
Receiving objects: 100% (1288/1288), 571.36 KiB | 1.65 MiB/s, done.
Resolving deltas: 100% (700/700), done.
➜  Desktop cd super-bot
➜  super-bot git:(master) go test ./...
go: downloading github.com/go-telegram-bot-api/telegram-bot-api v4.6.5-0.20200113063019-aa124ef1e84e+incompatible
go: downloading github.com/umputun/go-flags v1.5.1
go: downloading gopkg.in/yaml.v2 v2.2.8
go: downloading github.com/technoweenie/multipartstreamer v1.0.1
?   	github.com/radio-t/super-bot/app	[no test files]
ok  	github.com/radio-t/super-bot/app/bot	1.223s
ok  	github.com/radio-t/super-bot/app/events	1.905s
ok  	github.com/radio-t/super-bot/app/reporter	6.560s
ok  	github.com/radio-t/super-bot/app/storage	0.358s
➜  super-bot git:(master) go version
go version go1.14.1 darwin/amd64
```

**Comment by spiritofsim** [comment]
git clone https://github.com/radio-t/super-bot                                                                                                                                                    Cloning into 'super-bot'...                                                                                                                                                                               remote: Enumerating objects: 95, done.                                                                                                                                                                    remote: Counting objects: 100% (95/95), done.                                                                                                                                                             remote: Compressing objects: 100% (66/66), done.                                                                                                                                                          remote: Total 1288 (delta 56), reused 61 (delta 29), pack-reused 1193                                                                                                                                     Receiving objects: 100% (1288/1288), 571.36 KiB | 1.82 MiB/s, done.                                                                                                                                       Resolving deltas: 100% (700/700), done.                    

cd super-bot

go test ./...
?       github.com/radio-t/super-bot/app        [no test files]
2020/04/03 21:00:06 INFO  anecdote bot with http://rzhunemogu.ru/RandJSON.aspx?CType=1 and http://api.icndb.com/jokes/random
2020/04/03 21:00:06 INFO  anecdote bot with http://rzhunemogu.ru/RandJSON.aspx?CType=1 and http://api.icndb.com/jokes/random
2020/04/03 21:00:06 INFO  anecdote bot with http://rzhunemogu.ru/RandJSON.aspx?CType=1 and http://api.icndb.com/jokes/random
2020/04/03 21:00:06 WARN  failed to send request http://rzhunemogu.ru/RandJSON.aspx?CType=1, error=err
2020/04/03 21:00:06 INFO  anecdote bot with http://rzhunemogu.ru/RandJSON.aspx?CType=1 and http://api.icndb.com/jokes/random
2020/04/03 21:00:06 INFO  anecdote bot with http://rzhunemogu.ru/RandJSON.aspx?CType=1 and http://api.icndb.com/jokes/random
2020/04/03 21:00:06 WARN  failed to convert from json, error=invalid character 'o' in literal null (expecting 'u')
2020/04/03 21:00:06 INFO  anecdote bot with http://rzhunemogu.ru/RandJSON.aspx?CType=1 and http://api.icndb.com/jokes/random
2020/04/03 21:00:06 WARN  failed to send request http://api.icndb.com/jokes/random, error=err
2020/04/03 21:00:06 INFO  anecdote bot with http://rzhunemogu.ru/RandJSON.aspx?CType=1 and http://api.icndb.com/jokes/random
2020/04/03 21:00:06 INFO  WTF bot with 1m0s-10m0s interval
2020/04/03 21:00:06 INFO  BroadcastStatus bot with http://127.0.0.1:53669
2020/04/03 21:00:06 INFO  Broadcast started
2020/04/03 21:00:06 INFO  Broadcast finished
2020/04/03 21:00:06 INFO  Broadcast started
2020/04/03 21:00:06 INFO  Broadcast finished
2020/04/03 21:00:09 WARN  unable to create http://localhost:9873 request, net/http: nil Context
2020/04/03 21:00:09 INFO  Duck bot with duckduckgo-duckduckgo-zero-click-info.p.mashape.com
2020/04/03 21:00:09 INFO  Excerpt bot with https://ureadability.radio-t.com/api/content/v1/parser
2020/04/03 21:00:09 INFO  found a link http://radio-t.com
2020/04/03 21:00:09 INFO  found a link https://radio-t.com
2020/04/03 21:00:09 INFO  found a link https://radio-t.com/png
2020/04/03 21:00:09 INFO  ignore possible twitter link from blah https://twitter.com/radio_t/status/811670832510537730
2020/04/03 21:00:09 INFO  Excerpt bot with https://ureadability.radio-t.com/api/content/v1/parser
2020/04/03 21:00:09 INFO  found a link https://radio-t.com/p/2016/11/06/bot/
2020/04/03 21:00:09 INFO  found a link https://xxxx.radio-t.com
2020/04/03 21:00:09 WARN  parser error code 400 for https://ureadability.radio-t.com/api/content/v1/parser?token=123456&url=https://xxxx.radio-t.com
2020/04/03 21:00:09 INFO  news bot with api
2020/04/03 21:00:09 INFO  news bot with api
2020/04/03 21:00:09 INFO  news bot with api
2020/04/03 21:00:09 INFO  podcasts bot with api http://127.0.0.1:53690
2020/04/03 21:00:09 INFO  podcasts bot with api http://127.0.0.1:53692
2020/04/03 21:00:09 INFO  podcasts bot with api http://example.com
2020/04/03 21:00:09 INFO  podcasts bot with api http://127.0.0.1:53694
2020/04/03 21:00:09 INFO  prep-post bot with api http://example.com
2020/04/03 21:00:09 WARN  failed to check for new post, request http://example.com/last/1?categories=prep returned 400
2020/04/03 21:00:09 WARN  failed to check for new post, failed to send request http://example.com/last/1?categories=prep: error
2020/04/03 21:00:09 INFO  detected new prep topic https://radio-t.com/p/2020/02/11/prep-690/
2020/04/03 21:00:09 INFO  prep-post bot with api http://example.com
2020/04/03 21:00:09 INFO  detected new prep topic blah2
2020/04/03 21:00:09 INFO  created sys bot, data location=./../../data
--- FAIL: TestSys_OnMessage (0.00s)
    sys_test.go:13:
                Error Trace:    sys_test.go:13
                Error:          Not equal:
                                expected: bot.Response{Text:"_никто не знает. пока не надоест_", Send:true, Pin:false, Unpin:false, Preview:false, BanInterval:0}
                                actual  : bot.Response{Text:"_никто не знает. пока не надоест_\r", Send:true, Pin:false, Unpin:false, Preview:false, BanInterval:0}

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1,3 +1,3 @@
                                 (bot.Response) {
                                - Text: (string) (len=58) "_никто не знает. пока не надоест_",
                                + Text: (string) (len=59) "_никто не знает. пока не надоест_\r",
                                  Send: (bool) true,
                Test:           TestSys_OnMessage
    sys_test.go:14:
                Error Trace:    sys_test.go:14
                Error:          Not equal:
                                expected: bot.Response{Text:"_понг_", Send:true, Pin:false, Unpin:false, Preview:false, BanInterval:0}
                                actual  : bot.Response{Text:"_понг_\r", Send:true, Pin:false, Unpin:false, Preview:false, BanInterval:0}

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1,3 +1,3 @@
                                 (bot.Response) {
                                - Text: (string) (len=10) "_понг_",
                                + Text: (string) (len=11) "_понг_\r",
                                  Send: (bool) true,
                Test:           TestSys_OnMessage
    sys_test.go:15:
                Error Trace:    sys_test.go:15
                Error:          Not equal:
                                expected: bot.Response{Text:"_pong_", Send:true, Pin:false, Unpin:false, Preview:false, BanInterval:0}
                                actual  : bot.Response{Text:"_pong_\r", Send:true, Pin:false, Unpin:false, Preview:false, BanInterval:0}

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1,3 +1,3 @@
                                 (bot.Response) {
                                - Text: (string) (len=6) "_pong_",
                                + Text: (string) (len=7) "_pong_\r",
                                  Send: (bool) true,
                Test:           TestSys_OnMessage
    sys_test.go:16:
                Error Trace:    sys_test.go:16
                Error:          Not equal:
                                expected: bot.Response{Text:"_ Каждый французский солдат носит в своем ранце маршальский жезл._", Send:true, Pin:false, Unpin:false, Preview:false, BanInterval:0}
                                actual  : bot.Response{Text:"_ Каждый французский солдат носит в своем ранце маршальский жезл.\r_", Send:true, Pin:false, Unpin:false, Preview:false, BanInterval:0}

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1,3 +1,3 @@
                                 (bot.Response) {
                                - Text: (string) (len=120) "_ Каждый французский солдат носит в своем ранце маршальский жезл._",
                                + Text: (string) (len=121) "_ Каждый французский солдат носит в своем ранце маршальский жезл.\r_",
                                  Send: (bool) true,
                Test:           TestSys_OnMessage
2020/04/03 21:00:09 INFO  created sys bot, data location=./../../data
2020/04/03 21:00:09 INFO  created sys bot, data location=/tmp/no-such-place
2020/04/03 21:00:09 INFO  WTF bot with 24h0m0s-168h0m0s interval
FAIL
FAIL    github.com/radio-t/super-bot/app/bot    3.244s
ok      github.com/radio-t/super-bot/app/events (cached)
ok      github.com/radio-t/super-bot/app/reporter       (cached)
ok      github.com/radio-t/super-bot/app/storage        (cached)
FAIL

**Comment by paskal** [comment]
Can you please post the `go version` output and your operating system? I suspect it's not Linux\MacOS or you have older go version. If that's the case, I suggest running `docker build .` as it should produce the same result as one I've provided.

**Comment by spiritofsim** [comment]
go version                                                                                                                                                                              go version go1.13.4 windows/amd64

**Comment by umputun** [comment]
> Я попробую конечно, но это очень странно. Раньше все собиралось и тесты проходили

Скорее всего твой редактор поменял EOL когда ты загрузил/открыл `say.data`

**Comment by spiritofsim** [comment]
Немного переделал sys на bufio.scaner.
Теперь оно работает в любом случае
