### ISSUE TITLE
добавить бот-captcha

### ISSUE THREAD

**Issue by Semior001** [radio-t/super-bot#54]
идея следующая:
* человек приходит в группу, бот получает сообщение о том, что человек добавляется
* бот сохраняет id человека в каком-то хранилище (in-memory/bolt)
* бот отправляет в чат сообщение "тыкните на inline кнопку вот здесь, чтобы подтвердить, что вы не бот". Бот ждет нажатия какое-то установленное время (время поднимать из cli flags), а дальше - перманентный бан
    *  если человек пытается что-то писать, не тыкнув на кнопку - бот сразу же удаляет сообщение.
* человек тыкает
* бот удаляет человека из своего хранилища
* все радуются, мир спасен от спамеров, администраторы чата не тронуты

как-то вот так:
<img width="569" alt="Screen Shot 2020-04-12 at 6 30 51 PM" src="https://user-images.githubusercontent.com/3617699/79072814-bee41980-7ceb-11ea-9804-22f047157d0f.png">

**Comment by ffix** [comment]
Это не особо работает. Ботов заводят в чаты в полуручном режиме.

**Comment by umputun** [comment]
я не хочу издевательств над пользователями и против того, чтоб они что-то доказывали. Да и проблема ботов не настолько суровая
