### ISSUE TITLE
Отлавливать сообщения с рекламой

### ISSUE THREAD

**Issue by kunansy** [radio-t/super-bot#66]
Автоматически ловить сообщения с рекламой и банить ботов

**Comment by kunansy** [comment]
API тг бота позволяет определять, кто бот. Таких можно сразу банить без вопросов.

Неленивых спамеров, кто вручную это делает, можно отлавливать паттернами. Или вовсе запретить отправку ссылок по крайней мере на чаты тг. 

Как это сделать не тупо – хз, пишите идеи сюда, коллеги.

**Comment by obj** [comment]
В целом эти пару ботов в день прекрасно банятся и руками.

> API тг бота позволяет определять, кто бот. 

А можно увидеть ссылку на доку? Или мы про тип аккаунта? 
Если второе, то боты не могут заходить в чаты и сами там писать.

> Неленивых спамеров, кто вручную это делает, можно отлавливать паттернами. Или вовсе запретить отправку ссылок по крайней мере на чаты тг.

Слишком сложно. Запретить все ссылки не вариант. Запретить все картинки тоже не похоже на вариант.

**Comment by umputun** [comment]
это все решено в отдельном боте tg-spam
