### ISSUE TITLE
Не верная работа бота при "кулдауне" в личке

### ISSUE THREAD

**Issue by vosi** [radio-t/super-bot#67]
Если задолбать бота в личке, он перестает слушать задолбавшего в паблике, можно писать wtf! без последствий

<img width="904" alt="Screen Shot 2021-10-24 at 8 19 14 AM" src="https://user-images.githubusercontent.com/758024/138581893-ca14e44a-566e-47d6-b0d1-1f44bc9bcc6c.png">
<img width="903" alt="Screen Shot 2021-10-24 at 8 22 38 AM" src="https://user-images.githubusercontent.com/758024/138581966-9ad0e240-f54c-4561-b1ae-12ae3a8a6a2d.png">

**Comment by umputun** [comment]
@vosi у тебя плоучилось воспроизвести пробелму после теоретической починки в #67 ?

**Comment by vosi** [comment]
@umputun репродюсит, отписал в чатик

**Comment by vosi** [comment]
<img width="652" alt="Screen Shot 2021-11-09 at 10 42 50 PM" src="https://user-images.githubusercontent.com/758024/141001504-fd5e9c8c-3348-47bb-bd44-86720c7ea0e7.png">

**Comment by paskal** [comment]
@vosi возможно ли воспроизвести эту проблему сейчас?
