### ISSUE TITLE
Не проверять !,? в команде wtf{!,?}

### ISSUE THREAD

**Issue by adfslslddkds** [radio-t/super-bot#68]
Многие в торопях пишут команды wtf!, wtf?  без восклицательного и вопросительного знака просто wtf и не могут получить бан. Предлагаю перестать проверять символы !,? и выдавать бан просто за команду wtf в прямом и обратном написании.

**Comment by umputun** [comment]
это лишнее, кому надо действительно получить бан и без этого его получат
