### ISSUE TITLE
Проблема блокировки сообщений от имени каналов 

### ISSUE THREAD

**Issue by skar404** [radio-t/super-bot#71]
Недавно телеграм добавил возможность анонимно отправлять сообщения: [telegram.org info](https://telegram.org/blog/protected-content-delete-by-date-and-more#anonymous-posting-in-public-groups)

----

это поломало бан бота, сейчас бот не банит канал если человек от его имени написал, пример: 

<img width="483" alt="Screenshot 2021-12-21 at 18 59 16" src="https://user-images.githubusercontent.com/8483941/146960781-d3c37b25-6519-431e-a821-be896ba33174.png">

----- 

пример body который вернет telegram и из него нельзя достать id пользователя: 
```js
{
  "ok": true,
  "result": [
    {
      "update_id": 824523119,
      "message": {
        "message_id": 114,
        "from": { 
          # id telegram бота 
          "id": 136817688,
          "is_bot": true,
          "first_name": "Channel",
          "username": "Channel_Bot"
        },
        "sender_chat": {
          # id канала от имени которого было сообщение и нужно видимо банить его   
          "id": -1001132277055,
          "title": "test",
          "username": "test213151231asd123",
          "type": "channel"
        },
        "chat": {
          "id": -1001321436579,
          "title": "Тестовая группа",
          "username": "test_015",
          "type": "supergroup"
        },
        "date": 1640101804,
        "text": "test"
      }
    }
  ]
}
```

---

новый API метод для бана https://core.telegram.org/bots/api#banchatsenderchat

**Comment by paskal** [comment]
@skar404 спасибо большое за подробный багрепорт, вся информация оказалась релевантной.
