### ISSUE TITLE
Добавление бота для команды countdown!

### ISSUE THREAD

**Issue by desecho** [radio-t/super-bot#82]
Предлагаю добавить бота который бы реагировал на команду `countdown!` . Эта команда будет дублировать уже реализованный функционал на сайте в дополнение к команде `when?`. 

Должно быть полезно учитывая что время сейчас показывается в UTC, что не очевидно для многих.

**Comment by umputun** [comment]
я бы предложил просто добавить текст "до следущего подкаста: 6 дней, 5 часов, 17 минут" или что-то в этом роде в вывод `when?`
