### ISSUE TITLE
[fun bot] Drink suggestion

### ISSUE THREAD

**Issue by kazhuravlev** [radio-t/super-bot#84]
In order to choose the right and good drink for a weekend we can add a bit which will suggest a good one.

For example of will be looks like this:

```
>>>drink rum
<<<Dictador 20
```

Additional feature: super admins can say to bot what drink are they drinking right now. And users can ask about that.

**Comment by kazhuravlev** [comment]
Or may be something like `drink of week` command.

**Comment by umputun** [comment]
nah, i don't like the idea
