### ISSUE TITLE
[fun bot] Bet on the presence of the hosts

### ISSUE THREAD

**Issue by kazhuravlev** [radio-t/super-bot#85]
Users can make a bet (w/o money) on "who will not going to the next show" like

```
>>>bet without ksenks
>>>bet with ksenks,bobuk
```

After show is started - bot will show a results. 

Corner cases:
- [ ] User canot ask a current bets and results before show is started
- [ ] User can change his minds and make a new bet
- [ ] Use cannot change or add the bet after show is started

**Comment by umputun** [comment]
I don't think this is something useful, reminds me of a bunch of plugins we used to have but nobody cared to use it.
